CONTRIBUTORS.md, README.md
Others should add to the CONTRIBUTE.md file and read through the README.md file.
=> Updating development branch to reflect changes.

CONTRIBUTORS.md
Not sure if you didn't add your name @Emimint or if got lost somehow when I revert changes to the initial state of the repository but I added your name here to the contributor list
=> adds Emimint to the contributors list and alphabetizes the list

game.html
Hey Guys, I fixed a bug that was on the list item. Could you review it, please? Thanks!
=> [Bug / game.html / list items] #59

game.css, game.html
Does not follow a BEM naming convention but is a minimalistic approach to styling our game page
=> Feat 38/write mobile friendly css for game page/mnichols08

game.html, index.html
Hey Guys! I Add a footer containing a link to your team's GitHub repo. Could you review it? Thanks
=> Add a footer containing a link to your teams GitHub repo

game.html, input.html
Hey, Team!
I wrote a Semantic HTML for the Game Input Form Page. Could you review the file?
Thank you!
=> Semantic HTML for the Game Input Form Page

index.html, index_mobile.css
I added class selectors to index.html, made a new css file index_mobile.css to center all content.
=> Feat 29/write mobile friendly css for landing page/emimint

app.js, game.html, index.html, story.html
it was declared a variable for the anchor container. Could you guys review it? Thanks a lot :)
=> Declare a variable for the anchor container

app.js, stories.json
Hey team, could you review it?
=> create a function to collect Scenarios

app.js
I added a function that set the content of the anchor element to nothing.
=> add clear  function

src/views/init.js
hey Mikey! I wrote this function. Could you check if I did all correctly? Let me know if I got something wrong :)
thank you
=> feat-36/write-function-for-displaying-an-initial-interface-to-users/PaulaR-05

dist/site.webmanifest, package-lock.json, src/controller/index.js, src/views/renderInputPage.js, src/views/renderStoryPage.js
fixing variables inside the file controller/index.js
=> feat-132/function-that-render-story/PaulaR-05

docs/README.md
Add Maurice to README.md(Acknowledgments)
I googled it and found that should be done like this example below in the Acknowledgments session:
```
- [Maurice Butler](https://github.com/MauriceButler) is acknowledged with 🔣[Array.js](https://github.com/MauriceButler/badwords/blob/master/array.js) in the Contributors table. He is named as an author in the most recent version of the [BadWords](https://github.com/MauriceButler/badwords) repository.
139-we-need-to-give-credit-to-mauricebutler-for-badwords-array
```
Let me know if it should be done differently :)
=> 139-we-need-to-give-credit-to-mauricebutler-for-badwords-array

docs/README.md
=> adds darkmode image to file

docs/README.md
credits to Ksenia Kondrashova for the bubble animation
=> feat-77/animation-bluble-credit-on-readme/PaulaR-05

src/styles/components/_blobs.scss, src/styles/components/dots.scss, src/styles/components/rocket.scss, src/styles/pages/_print.scss, src/views/init.js
This should fix the print issue you mentioned can you let me know if it does or not?
=> Feature 168/create team page view/mnichols08

src/views/renderScenarios.js
Hey Guys! :)
I update the story page, so then we have different images for each scenario.
Can you check if it is correct the way I did it? In case not, let me know :)
Gracias/Thanks/Merci/Teşekkür ederim
=> Update images on story page

src/controller/index.js, src/styles/pages/_print.scss, src/views/renderInputPage.js, src/views/renderStoryPage.js
Hey @PaulaR-05 take a look and let me know if this solves the bug?
=> Bug 186/printscsss not rendering label/mnichols08

docs/README.md
Closes #185 
Hello, team! 
I added some info to our readme.md file, giving credits to designers who created some illustrations we used in our project.
Could you review it? Suggestions are welcome :)
Thank you
=> Add credits to creators on readme.md

src/styles/abstracts/_animations.scss, src/styles/components/_bugs.scss, src/styles/index.scss, src/views/init.js, src/views/renderBugs.js, src/views/renderTeamPage.js
This is a small feature that provides link to bug report / feedback form on google
=> Feat 194/bug report/mnichols08

src/model/devs.json
=> feat-204/developer-spotilight/PaulaR-05

docs/README.md
hey guys!
I add a bug/feedback report link to our README.md
Please, check this out and let me know  if you want to change something in there.
thanks!
=> Feat 205/add bug report on readme/paula r 05

docs/README.md, package.json
=> updates readme to use more unique phrases in acknowledgements section

src/styles/components/_button.scss, src/styles/pages/_storypage.scss
Hey can you please check if this fixed breakpoint issues on the story page? Will close #223
=> adds breakpoints to fix design on smaller phones

docs/README.md
last one for tonight i promise
=> changes image links

dist/favicon_io/site.webmanifest, dist/index.html, dist/site.webmanifest, src/styles/components/_button.scss, src/styles/pages/_root.scss, src/views/renderConfetti.js, src/views/renderHeader.js, src/views/renderStoryPage.js, src/views/team/renderTeamPage.js
Sorry @PaulaR-05 I know we thought we were done but I found this bug and had to fix
=> Fix/header bug/mnichols08

src/styles/base/_base.scss, src/styles/pages/_root.scss
Please forgive me! I thought of more stuff to add...This moves our background styles from html to the visuals class, which is really a better place for it, and also applies an animation of hue-rotate over a duration of 20000s a very very long time, so it gradually rotates the hue over time and really really really long time so you won't even notice it but it does change and the user may eventually notice and it's an easter egg at that point =)
This is the effect sped up to 1s duration to show what it does over 20000s
=> Feature/hue rotate/mnichols08
